### ISSUE TITLE
Running GTS program reports an error

### ISSUE THREAD

**Issue by ZPFPHD** [chaoshangcs/GTS#24]
Hello author, I encountered the following error after executing the program

2023-08-20 13:56:10,199 - easytorch-env - INFO - Use devices 0.
2023-08-20 13:56:10,208 - easytorch-launcher - INFO - Initializing runner "<class 'basicts.runners.runner_zoo.gts_runner.GTSRunner'>"
2023-08-20 13:56:10,208 - easytorch-env - INFO - Disable TF32 mode
2023-08-20 13:56:10,210 - easytorch - INFO - Set ckpt save dir: 'checkpoints\GTS_10\242c54d509146ae01c7d2f66712ee8de'
2023-08-20 13:56:10,210 - easytorch - INFO - Building model.
2023-08-20 13:56:10,600 - easytorch-training - INFO - Building training data loader.
train len: 6116
2023-08-20 13:56:13,859 - easytorch-training - ERROR - Traceback (most recent call last):
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\launcher\launcher.py", line 31, in training_func
    runner.train(cfg)
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\core\runner.py", line 317, in train
    self.init_training(cfg)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\base_tsf_runner.py", line 81, in init_training
    self.setup_graph(cfg=cfg, train=True)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\base_tsf_runner.py", line 68, in setup_graph
    self.forward(data=data, epoch=1, iter_num=0, train=train)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\runner_zoo\gts_runner.py", line 68, in forward
    prediction_data, pred_adj, prior_adj = self.model(history_data=history_data, future_data=future_data_4_dec, batch_seen=iter_num, epoch=epoch)       
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\pycharmproject\BasicTS-master\basicts\archs\arch_zoo\gts_arch\gts_arch.py", line 262, in forward
    x = self.conv1(x)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: expected output_padding to be a single integer value or a list of 1 values to match the convolution dimensions, but got output_padding=[0, 0]

Traceback (most recent call last):
  File "D:\pycharmproject\BasicTS-master\examples\run.py", line 63, in <module>
    launch_training(args.cfg, args.gpus)
  File "D:\pycharmproject\BasicTS-master\basicts\launcher.py", line 30, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\launcher\launcher.py", line 86, in launch_training
    train_dist(cfg)
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\launcher\launcher.py", line 35, in training_func
    raise e
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\launcher\launcher.py", line 31, in training_func
    runner.train(cfg)
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\core\runner.py", line 317, in train
    self.init_training(cfg)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\base_tsf_runner.py", line 81, in init_training
    self.setup_graph(cfg=cfg, train=True)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\base_tsf_runner.py", line 68, in setup_graph
    self.forward(data=data, epoch=1, iter_num=0, train=train)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\runner_zoo\gts_runner.py", line 68, in forward
    prediction_data, pred_adj, prior_adj = self.model(history_data=history_data, future_data=future_data_4_dec, batch_seen=iter_num, epoch=epoch)       
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\pycharmproject\BasicTS-master\basicts\archs\arch_zoo\gts_arch\gts_arch.py", line 262, in forward
    x = self.conv1(x)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: expected output_padding to be a single integer value or a list of 1 values to match the convolution dimensions, but got output_padding=[0, 0]

I haven't figured out what the mistake was. please help me

**Comment by lxy51** [comment]
Same question
